accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('dashboard',views.dashboard,name='dashboard')
]

pages/urls.py
from django.urls import path
from .views import index,about

urlpatterns = [
    path('',index,name='index'),
    path('about',about,name='about')
]

realestate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('pages.urls')),
    path('admin/', admin.site.urls),
    path('listings/',include('listings.urls'),),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('contacts/',include('contacts.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/components/_alerts.html
{% if messages%}
{% for message in messages %}
<div class="container" id='message'>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <strong>
        {% if message.level == DEFAULT_MESSAGE_LEVEL.ERROR %}
        ERROR: 
        
        {% else %}
        {{message.tags|title}}
        {% endif %}
        </strong>
        {{message}}
    </div>
</div>

{% endfor %}

{% endif%}

templates/components/_footer.html
{% load static %}
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> AK Real Estate
</footer>

templates/components/_navbar.html
{% load static %}

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'img/logo-1.png' %}" class="logo" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li 
          {% if '/' == request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-itemmr-3"
          {% endif %}>
            <a class="nav-link" href="{% url 'index' %}">Home</a>
          </li>
          <li 
          {% if 'about' in request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-itemmr-3"
          {% endif %}>
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li 
          {% if 'listings' in request.path %}
            class="nav-item active mr-3"
          {% else %}
            class="nav-itemmr-3"
          {% endif %}>
            <a class="nav-link" href="{% url 'listings' %}">Featured Listings</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
         {% if user.is_authenticated  %}
         <li 
            {% if 'dashboard' in request.path %}
            class="nav-item mr-3 active"
            {% else %}
            class="nav-item mr-3"
            {% endif %}>
              <a class="nav-link" href="{% url 'accounts:dashboard' %}">
            <i class="fas fa-tachometer-alt"></i></i> Dashboard</a>
          </li>
          <li
            class="nav-item mr-3">
              <a class="nav-link" 
              href="javascript:{document.getElementById('logout').submit()}">
            Logout</a>
            <form action="{% url 'accounts:logout' %}" method="POST" id='logout' >
            {% csrf_token %}
            <input type="hidden" ></form>
          </li>

         
         {% else %}
          <li 
            {% if 'register' in request.path %}
            class="nav-item mr-3 active"
            {% else %}
            class="nav-item mr-3"
            {% endif %}>
              <a class="nav-link" href="{% url 'accounts:register' %}">
              <i class="fas fa-user-plus"></i> Register</a>
          </li>
          <li 
            {% if 'login' in request.path %}
            class="nav-item mr-3 active"
            % else %}
            class="nav-item mr-3"
            {% endif %}>
              <a class="nav-link" href="{% url 'accounts:login' %}">
              <i class="fas fa-sign-in-alt"></i>

              Login</a>
          </li>
         {% endif %}
        </ul>
      </div>
    </div>
  </nav>

templates/components/_search_form.html
<section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">
          <h1 class="display-4 mb-4">
            Property Searching Just Got So Easy
          </h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae quas, asperiores eveniet vel nostrum magnam
            voluptatum tempore! Consectetur, id commodi!</p>
          <div class="search">
            <form action="{% url 'search' %}">
              <!-- Form Row 1 -->
              <div class="form-row">
                <div class="col-md-4 mb-3">
                  <label class="sr-only">Keywords</label>
                  <input type="text" name="keywords" class="form-control" placeholder="Keyword (Pool, Garage, etc)"
                  value="{{values.keywords}}">
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">City</label>
                  <input type="text" name="city" class="form-control" placeholder="City"
                  value="{{values.city}}">
                </div>
                <div class="col-md-4 mb-3">
                  <label class="sr-only">State</label>
                  <select name="state" class="form-control">
                    <option selected="true" disabled="disabled">State (All)</option>
                    {% for key,vl in state_choices.items %}
                        <option value="{{key}}" 
                        {% if key == values.state %}
                        selected
                        {% endif %}
                        >{{vl}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- Form Row 2 -->
              <div class="form-row">
                <div class="col-md-6 mb-3">
                  <label class="sr-only">Bedrooms</label>
                  <select name="bedrooms" class="form-control">
                    <option selected="true" disabled="disabled">Bedrooms (All)</option>
                    {% for key,vl in bedroom_choices.items %}
                        <option value="{{key}}"
                        {% if key == values.bedrooms %}
                        selected
                        {% endif %}
                        >{{vl}}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-md-6 mb-3">
                  <select name="price" class="form-control" id="type">
                    <option selected="true" disabled="disabled">Max Price (Any)</option>
                    {% for key,vl in price_choices.items %}
                        <option value="{{key}}"
                        {% if key == values.price %}
                        selected
                        {% endif %}>{{vl}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/components/_topbar.html
<!-- Top Bar -->
<section id="top-bar" class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <i class="fas fa-phone"></i> (617)-555-5555
        </div>
        <div class="col-md-4">
          <i class="fas fa-envelope-open"></i> contact@btrealestate.co
        </div>
        <div class="col-md-4">
          <div class="social text-right">
            <a href="#">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
              <i class="fab fa-facebook"></i>
            </a>
            <a href="#">
              <i class="fab fa-linkedin"></i>
            </a>
            <a href="#">
              <i class="fab fa-instagram"></i>
            </a>
            <a href="#">
              <i class="fab fa-pinterest"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>